all: libpyGeometry2.cpp libpyFactory2.cpp libpyEMData2.cpp libpyUtils2.cpp libpyFilter2.cpp

PYSTE = python /usr/bin/pyste.py -I../libEM

libpyGeometry2.cpp: geometry.pyste
	$(PYSTE) --module=libpyGeometry2 geometry.pyste

libpyFactory2.cpp: factory.pyste
	$(PYSTE) --module=libpyFactory2 factory.pyste

libpyEMData2.cpp: emdata.pyste
	$(PYSTE) --module=libpyEMData2  emdata.pyste

libpyUtils2.cpp: utils.pyste
	$(PYSTE) --module=libpyUtils2 utils.pyste

libpyFilter2.cpp: filter.pyste
	$(PYSTE) --module=libpyFilter2 filter.pyste 		 
	
