package:
    name: eman2
    version: {{ environ.get('EMAN_VERSION', '') }}

source:
    - path: {{ RECIPE_DIR }}/..
    - url: https://www.khronos.org/registry/OpenGL/api/GL/glext.h             # [win]
      folder: GL                                                              # [win]
    - url: https://www.khronos.org/registry/EGL/api/KHR/khrplatform.h         # [win]
      folder: KHR                                                             # [win]

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ cdt('mesa-libgl-devel') }}   # [linux]

    host:
        - eman-deps         {{ environ.get('EMAN_DEPS_VERSION', '') }}
        - libglu                          # [linux]
    
test:
  requires:
    - eman-deps     {{ environ.get('EMAN_DEPS_VERSION', '') }}
  
  source_files:
    - examples/mpi_test.py
    - programs/
    - tests/
    - rt/pyem/

  commands:
    - bash tests/run_tests.sh             # [not win]
    - call tests\run_tests.bat            # [win]
