package:
    name: eman2
    version: 2.21

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "msinttypes",  # [win]
            "python 2.7.*",
            "boost 1.63.*",
            "fftw-mpi",
            "numpy " ~ os.environ.get('NUMPY_VERSION') ~ ".*",  # [not win]
            "numpy 1.11.*",                                     # [win]
            "ftgl",
            "freetype",
            "gsl",
            "hdf5 1.8.18",
            "jpeg",
            "libtiff 4.0.9",
            "libpng 1.6.17",  # [linux]
            "libpng 1.6.32",  # [osx]
            "zlib",
            "matplotlib",
            "scipy 1.*",
            "ipython",
            "pyqt 4.*",
            "pyopengl 3.1.0",
            "theano 0.9.*",
            "scikit-learn 0.19.*",
            "bsddb",          # [not win]
            "openmpi 2.0.2",  # [not win]
            "pydusa",         # [not win]
            "nose",
    ] %}
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

build:
  script_env:
   - EMAN_TEST_SKIP  # [osx]

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py
    - tests/run_tests.sh
    - tests/run_tests.bat

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
