package:
    name: eman2
    version: 2.21

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "msinttypes",  # [win]
            "python 2.7.14",
            "boost 1.63.*",
            "fftw-mpi",
            "numpy 1.13.*",
            "ftgl",
            "freetype 2.8.*",  # [osx]
            "freetype 2.7.*",  # [not osx]
            "gsl",
            "hdf5 1.8.18",
            "jpeg",
            "libtiff 4.0.9",             # [not win]
            "libtiff 4.0.9 hafacce9_0",  # [win]
            "libpng 1.6.34",
            "zlib",
    ] %}
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
build:
  script_env:
   - EMAN_TEST_SKIP  # [osx]

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - examples/mpi_test.py
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py
    - tests/run_tests.sh
    - tests/run_tests.bat

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
