package:
    name: eman2
    version: 2.2

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "python 2.7.*",
            "boost 1.61.*",
            "fftw-mpi",
            "numpy x.x",  # [linux]
            "numpy",      # [not linux]
            "ftgl",
            "freetype",
            "gsl",
            "hdf5",
            "jpeg",
            "libtiff",
            "libpng",
            "zlib",
    ] %}
    
    build:
        - cmake
        - szip  # [win]
        - msinttypes  # [win]
        
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
        
        - szip  # [win]
        - bsddb  # [not win]
        - matplotlib
        - ipython
        - pyqt 4.*
        - pyopengl 3.1.0
        - theano
        - scikit-learn
        - pydusa  # [not win]

test:
  requires:
    - openmpi              # [not win]
  imports:
    - mpi                  # [not win]
    - EMAN2
    - libpyPDBReader2
    - libpyProjector2
    - libpyAnalyzer2
    - libpyPolarData2
    - libpyEMObject2
    - libpyTomoSeg2        # [not win]
    - libpyReconstructor2
    - libpyAverager2
    - libpyFundamentals2
    - libpyAligner2
    - libpyTransform2
    - libpyEMData2
    - libpyProcessor2
    - libpyMarchingCubes2  # [not win]
    - libpyGLUtils2
    - libpyGeometry2
    - libpyTypeConverter2
    - libpyPointArray2
    - libpyUtils2
    - libpyCmp2
    - libpyBoxingTools2
  
  source_files:
    - tests/run_prog_tests.sh
    - tests/programs_to_test.txt
    - tests/test_EMAN2DIR.py

  commands:
    - e2version.py
    - e2speedtest.py
    - e2display.py -h
    - test -f ${PREFIX}/examples/mpi_test.py                        # [not win]
    - mpirun -n 4 $(which python) ${PREFIX}/examples/mpi_test.py    # [not win]
    - if not exist %LIBRARY_PREFIX%\\examples\\mpi_test.py  exit 1  # [win]
    - bash tests/run_prog_tests.sh                                  # [not win]
    - python tests/test_EMAN2DIR.py
