package:
    name: eman2
    version: 2.2

source:
    path: {{ RECIPE_DIR }}/../..

requirements:
    {% set reqs_common = [
            "msinttypes",  # [win]
            "python 2.7.*",
            "boost 1.63.*",
            "fftw-mpi",
            "numpy x.x",  # [linux]
            "numpy",      # [not linux]
            "ftgl",
            "freetype",
            "gsl",
            "hdf5",
            "jpeg",
            "libtiff",
            "libpng",
            "zlib",
            "matplotlib",
            "ipython",
            "pyqt 4.*",
            "pyopengl 3.1.0",
            "theano",
            "scikit-learn",
            "bsddb",       # [not win]
            "pydusa",      # [not win]
            "nose",
    ] %}
    
    build:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}
    
    run:
        {% for req in reqs_common %}
        - {{ req }}
        {% endfor %}

build:
  script_env:
   - EMAN_TEST_SKIP  # [osx]

test:
  requires:
    - openmpi              # [not win]
  
  source_files:
    - tests/run_prog_tests.sh
    - tests/programs_no_test.txt
    - tests/test_EMAN2DIR.py
    - tests/run_tests.sh
    - tests/run_tests.bat

  commands:
    - bash tests/run_tests.sh                                # [not win]
    - call tests\run_tests.bat                               # [win]
