package:
    name: pydusa
    version: 1.15

source:
    url: https://github.com/cryoem/pydusa/archive/{{environ.get('GIT_PYDUSA_VERSION', 'v20170831')}}.tar.gz
    fn: pydusa-{{environ.get('GIT_PYDUSA_VERSION', 'v20170831')}}.tar.gz

build:
    number: 0
    skip: True  # [win or py3k]

requirements:
    build:
        - python
        - numpy x.x
        - fftw-mpi
    run:
        - numpy x.x
        - fftw-mpi

test:
  imports:
    - mpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
