from libpyUtils2 import *
from libpyTransform2 import *

MRC = EMUtil.ImageType.IMAGE_MRC
SPIDER = EMUtil.ImageType.IMAGE_SPIDER
SINGLE_SPIDER = EMUtil.ImageType.IMAGE_SINGLE_SPIDER
IMAGIC = EMUtil.ImageType.IMAGE_IMAGIC
HDF = EMUtil.ImageType.IMAGE_HDF
DM3 = EMUtil.ImageType.IMAGE_DM3
TIFF = EMUtil.ImageType.IMAGE_TIFF
PGM = EMUtil.ImageType.IMAGE_PGM
LST = EMUtil.ImageType.IMAGE_LST
PIF = EMUtil.ImageType.IMAGE_PIF
VTK = EMUtil.ImageType.IMAGE_VTK
PNG = EMUtil.ImageType.IMAGE_PNG
SAL = EMUtil.ImageType.IMAGE_SAL
ICOS = EMUtil.ImageType.IMAGE_ICOS
EMIM = EMUtil.ImageType.IMAGE_EMIM
GATAN2 = EMUtil.ImageType.IMAGE_GATAN2
AMIRA = EMUtil.ImageType.IMAGE_AMIRA
XPLOR = EMUtil.ImageType.IMAGE_XPLOR
EM = EMUtil.ImageType.IMAGE_EM
IMAGE_UNKNOWN = EMUtil.ImageType.IMAGE_UNKNOWN


EULER_EMAN = Transform3D.EulerType.EMAN
EULER_IMAGIC = Transform3D.EulerType.IMAGIC
EULER_SPIN = Transform3D.EulerType.SPIN
EULER_QUATERNION = Transform3D.EulerType.QUATERNION
EULER_SGIROT = Transform3D.EulerType.SGIROT
EULER_SPIDER = Transform3D.EulerType.SPIDER
EULER_MRC = Transform3D.EulerType.MRC


EM_UNKNOWN = EMUtil.EMDataType.EM_UNKNOWN
EM_CHAR = EMUtil.EMDataType.EM_CHAR
EM_UCHAR = EMUtil.EMDataType.EM_UCHAR
EM_SHORT = EMUtil.EMDataType.EM_SHORT
EM_USHORT = EMUtil.EMDataType.EM_USHORT
EM_INT = EMUtil.EMDataType.EM_INT
EM_UINT = EMUtil.EMDataType.EM_UINT
EM_FLOAT = EMUtil.EMDataType.EM_FLOAT
EM_DOUBLE = EMUtil.EMDataType.EM_DOUBLE
EM_SHORT_COMPLEX = EMUtil.EMDataType.EM_SHORT_COMPLEX
EM_USHORT_COMPLEX = EMUtil.EMDataType.EM_USHORT_COMPLEX
EM_FLOAT_COMPLEX = EMUtil.EMDataType.EM_FLOAT_COMPLEX

