find_package(PythonInterp REQUIRED)
find_package(PythonLibs   REQUIRED)

set(PYTHON_INCLUDE_PATH ${PYTHON_INCLUDE_DIRS} CACHE PATH "")
set(PYTHON_LIBRARY      ${PYTHON_LIBRARIES}    CACHE PATH "")

message("PYTHON_EXECUTABLE:   ${PYTHON_EXECUTABLE}")
message("PYTHON_LIBRARIES:    ${PYTHON_LIBRARIES}")
message("PYTHON_INCLUDE_DIRS: ${PYTHON_INCLUDE_DIRS}")
message("PYTHON_INCLUDE_PATH: ${PYTHON_INCLUDE_PATH}")
message("PYTHON_INCLUDE_DIR:  ${PYTHON_INCLUDE_DIR}")

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Python
		REQUIRED_VARS PYTHON_EXECUTABLE PYTHON_LIBRARIES PYTHON_INCLUDE_DIR
		)
