find_package(Freetype REQUIRED)

message("FREETYPE_LIBRARIES:    ${FREETYPE_LIBRARIES}")
message("FREETYPE_INCLUDE_DIRS: ${FREETYPE_INCLUDE_DIRS}")

IF (ENABLE_STATIC_FTGL)
	IF(WIN32)
		CHECK_REQUIRED_LIB(FREETYPE freetype ft2build.h "" "")
	ENDIF(WIN32)
ENDIF (ENABLE_STATIC_FTGL)
