find_package(JPEG REQUIRED)

message_var(JPEG_LIBRARIES)

if(JPEG_FOUND AND NOT TARGET JPEG::JPEG)
	add_library(JPEG::JPEG INTERFACE IMPORTED)
	set_target_properties(JPEG::JPEG PROPERTIES
						  INTERFACE_LINK_LIBRARIES      "${JPEG_LIBRARIES}"
						  INTERFACE_COMPILE_DEFINITIONS USE_JPEG
						  )
endif()
