find_package(OpenGL REQUIRED)
set(GL_LIBRARY       ${OPENGL_gl_LIBRARY} CACHE PATH "")
set(GLU_LIBRARY      ${OPENGL_LIBRARIES}  CACHE PATH "")
set(GL_INCLUDE_PATH  ${OPENGL_INCLUDE_DIR})
set(GLU_INCLUDE_PATH ${OPENGL_INCLUDE_DIR})

message("OPENGL_LIBRARY:     ${OPENGL_LIBRARY}")
message("GL_LIBRARY:         ${GL_LIBRARY}")
message("GLU_LIBRARY:        ${GLU_LIBRARY}")
message("OPENGL_INCLUDE_DIR: ${OPENGL_INCLUDE_DIR}")
message("GL_INCLUDE_PATH:    ${GL_INCLUDE_PATH}")
message("GLU_INCLUDE_PATH:   ${GLU_INCLUDE_PATH}")

ADD_DEFINITIONS(-DUSE_OPENGL)
