#!/usr/bin/env python
# Launch ipython with an appropriate profile

from EMAN2 import *
from Golem import *
try:
	from IPython.Shell import IPShellEmbed
	banner = "Welcome to Golem."
	ipshell = IPShellEmbed(banner="Welcome to Golem.\n")
	ipshell()
except:
	print 'Please install "ipython".'


