#!/usr/bin/env python
# Launch ipython with an appropriate profile

from EMAN2 import *
from IPython.Shell import IPShellEmbed
banner = "Welcome to Sparx."
ipshell = IPShellEmbed(banner="Welcome to Sparx.\n")
ipshell()


