#!/usr/bin/env python
# Launch ipython with an appropriate profile

from EMAN2 import *
try:
	from IPython.Shell import IPShellEmbed
	banner = "Welcome to Sparx."
	ipshell = IPShellEmbed(banner="Welcome to Sparx.\n")
	ipshell()
except:
	print 'Please install "ipython".'


