# -*- mode: yaml -*-

name: Tag new version
on:
  push:
    branches:
      - master

jobs:
  bump-and-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Parse commit message for bump type
        run: |
          if ${{ contains(github.event.head_commit.message, '[bump patch]') || contains(github.event.head_commit.message, '[ci build]') }}; then
            echo "bump=patch" >> $GITHUB_ENV
          elif ${{ contains(github.event.head_commit.message, '[bump minor]') }}; then
            echo "bump=minor" >> $GITHUB_ENV
          elif ${{ contains(github.event.head_commit.message, '[bump major]') }}; then
            echo "bump=major" >> $GITHUB_ENV
          fi

      - name: Checkout eman2
        if: ${{ env.bump }}
        uses: actions/checkout@v4
        with:
          path: 'eman2'
          fetch-depth: 0

      - name: Set up Git user
        if: ${{ env.bump }}
        run: |
          git config --global user.email "eman.github@gmail.com"
          git config --global user.name "eman-bot"

      - name: Bump and tag new version
        if: ${{ env.bump }}
        run: |
          cd eman2
          git fetch --tags
          latest_tag=$(git tag -l 'v*' --sort=-v:refname | head -n 1)
          raw_version=${latest_tag#v}

          IFS='.' read -r major minor patch <<< "$raw_version"

          case "${{ env.bump }}" in
            major)
              major=$((major + 1))
              minor=0
              patch=0
              ;;
            minor)
              minor=$((minor + 1))
              patch=0
              ;;
            patch)
              patch=$((patch + 1))
              ;;
          esac

          new_version="${major}.${minor}.${patch}"
          echo "NEW_VERSION_STRING=$new_version" >> $GITHUB_ENV
          
          sed -i "s/VERSION\s*[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*/VERSION ${new_version}/" CMakeLists.txt

          git add CMakeLists.txt
          git commit -m "v${new_version}"
          git tag -f "v${new_version}"
          git push origin master "v${new_version}"

      - name: Checkout eman-feedstock
        if: ${{ env.bump }}
        uses: actions/checkout@v4
        with:
          repository: cryoem/eman-feedstock
          token: ${{ secrets.FEEDSTOCK_TOKEN }}
          path: 'eman-feedstock'
          persist-credentials: false

      - name: Update version in eman-feedstock
        if: ${{ env.bump }}
        env:
          PASSED_VERSION: ${{ env.NEW_VERSION_STRING }}
          FEEDSTOCK_AUTH: ${{ secrets.FEEDSTOCK_TOKEN }}
        run: |
          cd eman-feedstock
          
          curl -L -o release.dar.gz "https://github.com/cryoem/eman2/archive/v${PASSED_VERSION}.tar.gz"
          
          calculated_hash=$(sha256sum release.tar.gz | awk '{ print $1 }')
          echo "Calculated SHA256: ${calculated_hash}"
          rm release.tar.gz

          sed -i "s/set\\s*version\\s*=\\s*\"[0-9][0-9]*\\.[0-9][0-9]*\\.[0-9][0-9]*\"/set version = \"${PASSED_VERSION}\"/" recipe/meta.yaml
          sed -i "s/set\\s*sha256\\s*=\\s*\"[^\"]*\"/set sha256 = \"${calculated_hash}\"/" recipe/meta.yaml
          sed -i 's/set\s*build\s*=\s*[0-9][0-9]*/set build = 0/' recipe/meta.yaml

          git add recipe/meta.yaml
          git commit -m "v${PASSED_VERSION} and hash updates"
          git remote set-url origin "https://x-access-token:${FEEDSTOCK_AUTH}@github.com/cryoem/eman-feedstock.git"
          
          git push origin master
